package az.iptv.fplayer.ui.text

import az.iptv.fplayer.data.preferences.AppLanguage

data class AppTexts(
    val allChannels: String,
    val recentChannels: String,
    val categories: String,
    val exitHint: String,
    val exitTitle: String,
    val exitSubtitle: String,
    val program: String,
    val noInfo: String,
    val mediaOptions: String,
    val audio: String,
    val subtitles: String,
    val off: String,
    val favorite: String,
    val locked: String,
    val playlistSource: String,
    val playlistSubtitle: String,
    val sourceM3u: String,
    val sourceXtream: String,
    val m3uSubtitle: String,
    val xtreamSubtitle: String,
    val playlistName: String,
    val serverUrl: String,
    val username: String,
    val password: String,
    val addPlaylist: String,
    val updatePlaylist: String,
    val loadRefresh: String,
    val loadingChannels: String,
    val channelsFound: (Int) -> String,
    val playlistLimit: String,
    val savedPlaylists: String,
    val active: String,
    val switchTo: String,
    val player: String,
    val recommended: String,
    val manualVlc: String,
    val settings: String,
    val playlists: String,
    val videoPlayer: String,
    val audioDecoder: String,
    val language: String,
    val theme: String,
    val themeClassic: String,
    val themeClassicHint: String,
    val themeDrmPlay: String,
    val themeDrmPlayHint: String,
    val az: String,
    val en: String,
    val auto: String,
    val hardware: String,
    val software: String,
    val autoHint: String,
    val hwHint: String,
    val swHint: String,
    val version: String,
    val load: String,
    val loading: String,
    val channelsCount: (Int) -> String,
    val back: String,
    val edit: String,
    val chooseSource: String,
    val connectionDetails: String,
    val welcomeSetup: String,
    val stepLabel: (Int, Int) -> String,
    val playbackSettings: String,
    val showFps: String,
    val showFpsHint: String,
    val frameRateMatching: String,
    val frameRateMatchingHint: String,
    val rawAudioConvert: String,
    val rawAudioConvertHint: String,
    val tunneledPlayback: String,
    val tunneledPlaybackHint: String,
    val fix1080i: String,
    val fix1080iHint: String,
    val on: String,
    val watch: String,
    val movies: String,
    val series: String,
    val nowPlaying: String
)

fun appTexts(language: String): AppTexts =
    if (language == AppLanguage.EN.name) enTexts else azTexts

private val azTexts = AppTexts(
    allChannels = "Bütün kanallar",
    recentChannels = "Son kanallar",
    categories = "Kateqoriyalar",
    exitHint = "Çıxış üçün bir daha bas",
    exitTitle = "Çıxmaq istəyirsən?",
    exitSubtitle = "OK basanda tətbiq bağlanacaq",
    program = "Proqram",
    noInfo = "Məlumat yoxdur",
    mediaOptions = "Səs / Subtitr",
    audio = "Səs",
    subtitles = "Subtitrlər",
    off = "Bağlı",
    favorite = "Favori",
    locked = "Şifrəli",
    playlistSource = "Kanal mənbəyi",
    playlistSubtitle = "Mənbə seçin, siyahını yükləyin və istədiyiniz vaxt siyahılar arasında keçin",
    sourceM3u = "M3U Playlist",
    sourceXtream = "Xtream Codes",
    m3uSubtitle = "URL linkdən yüklə",
    xtreamSubtitle = "Server, istifadəçi, şifrə",
    playlistName = "Siyahı adı",
    serverUrl = "Server URL",
    username = "İstifadəçi adı",
    password = "Şifrə",
    addPlaylist = "Yeni siyahı əlavə et",
    updatePlaylist = "Siyahını yenilə",
    loadRefresh = "Yüklə / Yenilə",
    loadingChannels = "Kanallar yüklənir...",
    channelsFound = { count -> "✓ $count kanal tapıldı" },
    playlistLimit = "Eyni anda maksimum 10 siyahı saxlamaq olar.",
    savedPlaylists = "Saxlanmış siyahılar",
    active = "Aktiv",
    switchTo = "Keç",
    player = "Oynadıcı",
    recommended = "Tövsiyə edilir",
    manualVlc = "Manual quraşdırma lazımdır",
    settings = "Ayarlar",
    playlists = "Siyahılar",
    videoPlayer = "Video oynadıcı",
    audioDecoder = "Audio dekoder",
    language = "Dil",
    theme = "Tema",
    themeClassic = "Klassik",
    themeClassicHint = "Movcud mavi-boz dizayn",
    themeDrmPlay = "DRM Play",
    themeDrmPlayHint = "Qara fon, sari vurgu",
    az = "Azərbaycanca",
    en = "English",
    auto = "Avto",
    hardware = "Aparat",
    software = "Proqram",
    autoHint = "Avto: əvvəl aparat dekoderi, xəta olarsa proqram dekoderi yoxlanır.",
    hwHint = "HW: yalnız aparat dekoderi. Səs problemi varsa Avto və ya SW seçin.",
    swHint = "SW: proqram dekoderi. Bəzi RAW kanallarda daha sabit ola bilər.",
    version = "Versiya",
    load = "Yüklə",
    loading = "Yüklənir...",
    channelsCount = { count -> "✓ $count kanal" },
    back = "Geri",
    edit = "Düzəliş",
    chooseSource = "Mənbə növünü seçin",
    connectionDetails = "Bağlantı məlumatları",
    welcomeSetup = "Başlamaq üçün kanal mənbəyi əlavə edin",
    stepLabel = { current, total -> "Addım $current / $total" },
    playbackSettings = "Oynatma ayarları",
    showFps = "FPS göstəricisi",
    showFpsHint = "Kanal məlumat kartında yayının FPS dəyəri görünür",
    frameRateMatching = "Kadr tezliyi uyğunlaşdırması",
    frameRateMatchingHint = "Ekran yenilənmə tezliyi yayının FPS-inə uyğunlaşdırılır (Android 11+)",
    rawAudioConvert = "RAW səs çevirmə",
    rawAudioConvertHint = "Səs kəsik-kəsik gəlirsə aktiv edin — passthrough əvəzinə PCM istifadə olunur",
    tunneledPlayback = "Tunel oynatma rejimi",
    tunneledPlaybackHint = "Bəzi cihazlarda daha axıcı görüntü verir. Aktiv olanda FPS məlumatı görünmür",
    fix1080i = "1080i axıcılıq düzəlişi",
    fix1080iHint = "Android 14-də 1080i yayınların 15fps kimi görünmə xətasını aradan qaldırır",
    on = "Aktiv",
    watch = "İzlə",
    movies = "Kino",
    series = "Seriallar",
    nowPlaying = "İndi oxudulur"
)

private val enTexts = AppTexts(
    allChannels = "All channels",
    recentChannels = "Recent channels",
    categories = "Categories",
    exitHint = "Press once more to exit",
    exitTitle = "Exit app?",
    exitSubtitle = "Press OK to close the app",
    program = "Program",
    noInfo = "No information",
    mediaOptions = "Audio / Subtitles",
    audio = "Audio",
    subtitles = "Subtitles",
    off = "Off",
    favorite = "Favorite",
    locked = "Locked",
    playlistSource = "Channel source",
    playlistSubtitle = "Choose a source, load channels, and switch between saved playlists anytime",
    sourceM3u = "M3U Playlist",
    sourceXtream = "Xtream Codes",
    m3uSubtitle = "Load from URL",
    xtreamSubtitle = "Server, username, password",
    playlistName = "Playlist name",
    serverUrl = "Server URL",
    username = "Username",
    password = "Password",
    addPlaylist = "Add new playlist",
    updatePlaylist = "Update playlist",
    loadRefresh = "Load / Refresh",
    loadingChannels = "Loading channels...",
    channelsFound = { count -> "✓ $count channels found" },
    playlistLimit = "You can keep up to 10 playlists at the same time.",
    savedPlaylists = "Saved playlists",
    active = "Active",
    switchTo = "Switch",
    player = "Player",
    recommended = "Recommended",
    manualVlc = "Manual setup needed",
    settings = "Settings",
    playlists = "Playlists",
    videoPlayer = "Video player",
    audioDecoder = "Audio decoder",
    language = "Language",
    theme = "Theme",
    themeClassic = "Classic",
    themeClassicHint = "Current blue-gray design",
    themeDrmPlay = "DRM Play",
    themeDrmPlayHint = "Black base, yellow accents",
    az = "Azerbaijani",
    en = "English",
    auto = "Auto",
    hardware = "Hardware",
    software = "Software",
    autoHint = "Auto: uses hardware decoding first and falls back to software if needed.",
    hwHint = "HW: hardware decoding only. Try Auto or SW if audio is missing.",
    swHint = "SW: software decoding, useful for some raw audio channels.",
    version = "Version",
    load = "Load",
    loading = "Loading...",
    channelsCount = { count -> "✓ $count channels" },
    back = "Back",
    edit = "Edit",
    chooseSource = "Choose source type",
    connectionDetails = "Connection details",
    welcomeSetup = "Add a channel source to get started",
    stepLabel = { current, total -> "Step $current / $total" },
    playbackSettings = "Playback settings",
    showFps = "FPS indicator",
    showFpsHint = "Shows the stream FPS on the channel info card",
    frameRateMatching = "Frame rate matching",
    frameRateMatchingHint = "Matches the display refresh rate to the stream FPS (Android 11+)",
    rawAudioConvert = "RAW audio conversion",
    rawAudioConvertHint = "Enable if audio stutters — decodes to PCM instead of passthrough",
    tunneledPlayback = "Tunneled playback",
    tunneledPlaybackHint = "Smoother video on some devices. FPS info is hidden while active",
    fix1080i = "1080i smoothness fix",
    fix1080iHint = "Fixes 1080i streams looking like 15fps on Android 14",
    on = "On",
    watch = "Watch",
    movies = "Movies",
    series = "Series",
    nowPlaying = "Now playing"
)
