package az.iptv.fplayer.ui.text

import az.iptv.fplayer.data.preferences.AppLanguage

data class AppTexts(
    val allChannels: String,
    val recentChannels: String,
    val categories: String,
    val exitHint: String,
    val exitTitle: String,
    val exitSubtitle: String,
    val program: String,
    val noInfo: String,
    val mediaOptions: String,
    val audio: String,
    val subtitles: String,
    val off: String,
    val favorite: String,
    val adultPin: String,
    val adultPinHint: String,
    val savePin: String,
    val locked: String,
    val enterPin: String,
    val wrongPin: String,
    val playlistSource: String,
    val playlistSubtitle: String,
    val sourceM3u: String,
    val sourceXtream: String,
    val m3uSubtitle: String,
    val xtreamSubtitle: String,
    val playlistName: String,
    val serverUrl: String,
    val username: String,
    val password: String,
    val addPlaylist: String,
    val updatePlaylist: String,
    val loadRefresh: String,
    val loadingChannels: String,
    val channelsFound: (Int) -> String,
    val playlistLimit: String,
    val savedPlaylists: String,
    val active: String,
    val switchTo: String,
    val player: String,
    val recommended: String,
    val manualVlc: String,
    val settings: String,
    val playlists: String,
    val videoPlayer: String,
    val audioDecoder: String,
    val language: String,
    val az: String,
    val en: String,
    val auto: String,
    val hardware: String,
    val software: String,
    val autoHint: String,
    val hwHint: String,
    val swHint: String,
    val version: String,
    val load: String,
    val loading: String,
    val channelsCount: (Int) -> String
)

fun appTexts(language: String): AppTexts =
    if (language == AppLanguage.EN.name) enTexts else azTexts

private val azTexts = AppTexts(
    allChannels = "Bütün kanallar",
    recentChannels = "Son kanallar",
    categories = "Kateqoriyalar",
    exitHint = "Çıxış üçün bir daha bas",
    exitTitle = "Çıxmaq istəyirsən?",
    exitSubtitle = "OK basanda tətbiq bağlanacaq",
    program = "Proqram",
    noInfo = "Məlumat yoxdur",
    mediaOptions = "Səs / Subtitr",
    audio = "Səs",
    subtitles = "Subtitrlər",
    off = "Bağlı",
    favorite = "Favori",
    adultPin = "Adult PIN",
    adultPinHint = "Adult kanalları üçün şifrə",
    savePin = "PIN saxla",
    locked = "Şifrəli",
    enterPin = "PIN daxil edin",
    wrongPin = "PIN yanlışdır",
    playlistSource = "Kanal mənbəyi",
    playlistSubtitle = "Mənbə seçin, siyahını yükləyin və istədiyiniz vaxt siyahılar arasında keçin",
    sourceM3u = "M3U Playlist",
    sourceXtream = "Xtream Codes",
    m3uSubtitle = "URL linkdən yüklə",
    xtreamSubtitle = "Server, istifadəçi, şifrə",
    playlistName = "Siyahı adı",
    serverUrl = "Server URL",
    username = "İstifadəçi adı",
    password = "Şifrə",
    addPlaylist = "Yeni siyahı əlavə et",
    updatePlaylist = "Siyahını yenilə",
    loadRefresh = "Yüklə / Yenilə",
    loadingChannels = "Kanallar yüklənir...",
    channelsFound = { count -> "✓ $count kanal tapıldı" },
    playlistLimit = "Eyni anda maksimum 10 siyahı saxlamaq olar.",
    savedPlaylists = "Saxlanmış siyahılar",
    active = "Aktiv",
    switchTo = "Keç",
    player = "Oynadıcı",
    recommended = "Tövsiyə edilir",
    manualVlc = "Manual quraşdırma lazımdır",
    settings = "Ayarlar",
    playlists = "Siyahılar",
    videoPlayer = "Video oynadıcı",
    audioDecoder = "Audio dekoder",
    language = "Dil",
    az = "Azərbaycanca",
    en = "English",
    auto = "Avto",
    hardware = "Aparat",
    software = "Proqram",
    autoHint = "Avto: əvvəl aparat dekoderi, xəta olarsa proqram dekoderi yoxlanır.",
    hwHint = "HW: yalnız aparat dekoderi. Səs problemi varsa Avto və ya SW seçin.",
    swHint = "SW: proqram dekoderi. Bəzi RAW kanallarda daha sabit ola bilər.",
    version = "Versiya",
    load = "Yüklə",
    loading = "Yüklənir...",
    channelsCount = { count -> "✓ $count kanal" }
)

private val enTexts = AppTexts(
    allChannels = "All channels",
    recentChannels = "Recent channels",
    categories = "Categories",
    exitHint = "Press once more to exit",
    exitTitle = "Exit app?",
    exitSubtitle = "Press OK to close the app",
    program = "Program",
    noInfo = "No information",
    mediaOptions = "Audio / Subtitles",
    audio = "Audio",
    subtitles = "Subtitles",
    off = "Off",
    favorite = "Favorite",
    adultPin = "Adult PIN",
    adultPinHint = "Password for adult channels",
    savePin = "Save PIN",
    locked = "Locked",
    enterPin = "Enter PIN",
    wrongPin = "Wrong PIN",
    playlistSource = "Channel source",
    playlistSubtitle = "Choose a source, load channels, and switch between saved playlists anytime",
    sourceM3u = "M3U Playlist",
    sourceXtream = "Xtream Codes",
    m3uSubtitle = "Load from URL",
    xtreamSubtitle = "Server, username, password",
    playlistName = "Playlist name",
    serverUrl = "Server URL",
    username = "Username",
    password = "Password",
    addPlaylist = "Add new playlist",
    updatePlaylist = "Update playlist",
    loadRefresh = "Load / Refresh",
    loadingChannels = "Loading channels...",
    channelsFound = { count -> "✓ $count channels found" },
    playlistLimit = "You can keep up to 10 playlists at the same time.",
    savedPlaylists = "Saved playlists",
    active = "Active",
    switchTo = "Switch",
    player = "Player",
    recommended = "Recommended",
    manualVlc = "Manual setup needed",
    settings = "Settings",
    playlists = "Playlists",
    videoPlayer = "Video player",
    audioDecoder = "Audio decoder",
    language = "Language",
    az = "Azerbaijani",
    en = "English",
    auto = "Auto",
    hardware = "Hardware",
    software = "Software",
    autoHint = "Auto: uses hardware decoding first and falls back to software if needed.",
    hwHint = "HW: hardware decoding only. Try Auto or SW if audio is missing.",
    swHint = "SW: software decoding, useful for some raw audio channels.",
    version = "Version",
    load = "Load",
    loading = "Loading...",
    channelsCount = { count -> "✓ $count channels" }
)
